version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: sayHi
          command: |
            echo "Hello, from a simple sample project!"
            echo "Can a non-admin make a change?"
